#%RAML 1.0
title: SoapDistpatcher
baseUri: http://localhost:8080/servicios/{version}
mediaType:  [application/xml, application/json]
version: v1
types: 
  Factura:
    type: !include factura.xsd
  Payment:
    type: !include payment.xsd
/payment:
   get:
       description: Retorna la cantidad a pagar
       body:
         application/xml:
          type: Factura
          example: !include example.raml
       responses:
           200:
               body:
                  application/xml:
                    type: Payment
           404:
               description: La factura no existe
   post:
       description: Permite realizar el pago de la factura existente
       body:
          application/xml:
            type: Payment
            example: !include GetExample.raml
       responses:
           200:
               body:
                   application/xml:
                     properties:
                        idFactura: number
                        mensajeOK: string
           404:
               body:
                   application/xml:
                     properties:
                       idFactura: number
                       mensajeBad: string
   delete:
       description: Permite compensar el pago de la factura existente
       body:
         application/xml:
           type: Payment
           example: !include GetExample.raml
       responses:
           200:
               body:
                   application/xml:
                     properties:
                       idFactura: number
                       mensajeOK: string
           404:
               body:
                  application/xml:
                    properties:
                      idFactura: number
                      mensajeBad: string
